#! /bin/sh

#
# WM INDEPENDENT HOTKEYS
#

# terminal emulator
super + Return
	xfce4-terminal

# program launcher
super + space
	rofi -show drun

super + Tab
	rofi -show window


# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# BSPWM HOTKEYS
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
# super + {_,shift + }@w
	# bspc node -{c,k}

super + @q
	bspc node -c

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# swap the current node and the biggest window in the current desktop
super + g
	bspc node -s biggest.window.local

#
# state/flags
#

# set the window state
super + {t,shift + t,s}
	bspc node -t {tiled,pseudo_tiled,floating}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {ampersand,eacute,quotedbl,apostrophe,parenleft,minus,egrave,underscore,ccedilla,agrave}
    bspc desktop -f '^{1,2,3,4,5,6,7,8,9,10}'

super + {1-9}
    bspc node -d '^{1,2,3,4,5,6,7,8,9}'

#
# preselect
#

# preselect the direction
super + ctrl + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {ampersand,eacute,quotedbl,apostrophe,parenleft,minus,egrave,underscore,ccedilla}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
# super + ctrl + shift + space
# 	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}