#! /bin/sh

## Env
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
	ALTRED=$(xrdb -query | grep 'color9:'| awk '{print $NF}')
}
getcolors

## Configuration --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 1 2 3 4 5 6 7 8 9
		# bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

bspc config border_width 2
bspc config window_gap 6

bspc config split_ratio 0.5

bspc config focused_border_color "$ALTRED"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$RED"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst xfce4-power-manager

dunst &

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
# if [[ ! `pidof xfce-polkit` ]]; then
# 	/usr/lib/xfce-polkit/xfce-polkit &
# fi

# Lauch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Restore wallpaper
feh --bg-fill ~/Pictures/Wallpapers/5m5kLI9.png

# Start mpd
# exec mpd &

# Picom
picom &

# Start bspwm scripts
bsp_colors
bsp_bar
# bsp_comp
# bsp_float &